### PR TITLE
Updated directions in tsv

### PR DESCRIPTION
**Pull request by danieljwilson**

### CODE REVIEW

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
@danieljwilson we know better now - let's make sure to run the docker command shown in the README to update the index.html using the survey.tsv!

**Comment by danieljwilson** [comment]
Okay it has been updated!

**Comment by vsoch** [comment]
There we go! You can add yourself to the contributor list here too if you like. it's a small change but it's a contribution!

**Comment by danieljwilson** [comment]
Ah, thanks - but I will save that for a more substantial contribution 🙂

**Pull request merged**
